package sharedServices

//goland:noinspection ALL
const (
	STATUS_ACTIVE    = "ACTIVE"
	STATUS_COMPLETED = "COMPLETED"
	STATUS_CONFIRMED = "CONFIRMED"
	STATUS_FAILED    = "FAILED"
	STATUS_INACTIVE  = "INACTIVE"
	STATUS_LINKED    = "LINKED"
	STATUS_PENDING   = "PENDING"
	STATUS_SUCCESS   = "SUCCESS"
	STATUS_UNKNOWN   = "UNKNOWN"
)
