package sharedServices

//goland:noinspection ALL
const (
	PAYLOAD_SUBJECT_FN      = "SUBJECT"
	PAYLOAD_CLAIMS_FN       = "CLAIMS"
	PAYLOAD_AUDIENCE_FN     = "AUDIENCE"
	PAYLOAD_REQUESTOR_ID_FN = "REQUESTOR_ID"
	PAYLOAD_EXPIRES_FN      = "EXPIRES"
	PAYLOAD_ISSUER_FN       = "ISSUER"
	PAYLOAD_ISSUED_AT_FN    = "ISSUED_AT"
)
