// Package constant_type_vars
/*
This file contains USA states and postal codes

RESTRICTIONS:
	- Do not edit this comment section.

NOTES:
    To improve code readability, the constant names do not follow camelCase.
	Do not remove IDE inspection directives

COPYRIGHT and WARRANTY:
	Copyright 2022
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/
package constant_type_vars

//goland:noinspection ALL
const (
BASH_COLOR_RESET = "\033[0m"
BASH_COLOR_RED = "\033[31m"
BASH_COLOR_GREEN = "\033[32m"
BASH_COLOR_YELLOW = "\033[33m"
BASH_COLOR_BLUE = "\033[34m"
BASH_COLOR_PURPLE = "\033[35m"
BASH_COLOR_CYAN = "\033[36m"
BASH_COLOR_WHITE = "\033[37m"
)

//goland:noinspection ALL
const (
WEBSAFE_ALICE_BLUE = "#F0F8FF"
WEBSAFE_ANTIQUE_WHITE = "#FAEBD7"
WEBSAFE_AQUA = "#00FFFF"
WEBSAFE_AQUA_MARINE = "#7FFFD4"
WEBSAFE_AZURE = "#F0FFFF"
WEBSAFE_BEIGE = "#F5F5DC"
WEBSAFE_BISQUE = "#FFE4C4"
WEBSAFE_BLACK = "#000000"
WEBSAFE_BLANCHED_ALMOND = "#FFEBCD"
WEBSAFE_BLUE = "#0000FF"
WEBSAFE_BLUE_VIOLET = "#8A2BE2"
WEBSAFE_BROWN = "#A52A2A"
WEBSAFE_BURLY_WOOD = "#DEB887"
WEBSAFE_CADET_BLUE = "#5F9EA0"
WEBSAFE_CHART_REUSE = "#7FFF00"
WEBSAFE_CHOCOLATE = "#D2691E"
WEBSAFE_CORAL = "#FF7F50"
WEBSAFE_CORN_FLOWER_BLUE = "#6495ED"
WEBSAFE_CORN_SILK = "#FFF8DC"
WEBSAFE_CRIMSON = "#DC143C"
WEBSAFE_CYAN = "#00FFFF"
WEBSAFE_DARK_BLUE = "#00008B"
WEBSAFE_DARK_CYAN = "#008B8B"
WEBSAFE_DARK_GOLDEN_ROD = "#B8860B"
WEBSAFE_DARK_GRAY = "#A9A9A9"
WEBSAFE_DARK_GREEN = "#006400"
WEBSAFE_DARK_KHAKI = "#BDB76B"
WEBSAFE_DARK_MAGENTA = "#8B008B"
WEBSAFE_DARK_OLIVE_GREEN = "#556B2F"
WEBSAFE_DARK_ORANGE = "#FF8C00"
WEBSAFE_DARK_ORCHID = "#9932CC"
WEBSAFE_DARK_RED = "#8B0000"
WEBSAFE_DARK_SALMON = "#E9967A"
WEBSAFE_DARK_SEA_GREEN = "#8FBC8F"
WEBSAFE_DARK_SLATE_BLUE = "#483D8B"
WEBSAFE_DARK_SLATE_GRAY = "#2F4F4F"
WEBSAFE_DARK_TURQUOISE = "#00CED1"
WEBSAFE_DARK_VIOLET = "#9400D3"
WEBSAFE_DEEP_PINK = "#FF1493"
WEBSAFE_DEEP_SKY_BLUE = "#00BFFF"
WEBSAFE_DIMG_RAY = "#696969"
WEBSAFE_DODGER_BLUE = "#1E90FF"
WEBSAFE_FIRE_BRICK = "#B22222"
WEBSAFE_FLORAL_WHITE = "#FFFAF0"
WEBSAFE_FOREST_GREEN = "#228B22"
WEBSAFE_FUCHSIA = "#FF00FF"
WEBSAFE_GAINSBORO = "#DCDCDC"
WEBSAFE_GHOST_WHITE = "#F8F8FF"
WEBSAFE_GOLD = "#FFD700"
WEBSAFE_GOLDEN_ROD = "#DAA520"
WEBSAFE_GRAY = "#808080"
WEBSAFE_GREEN = "#008000"
WEBSAFE_GREEN_YELLOW = "#ADFF2F"
WEBSAFE_HONEY_DEW = "#F0FFF0"
WEBSAFE_HOT_PINK = "#FF69B4"
WEBSAFE_INDIAN_RED = "#CD5C5C"
WEBSAFE_INDIGO = "#4B0082"
WEBSAFE_IVORY = "#FFFFF0"
WEBSAFE_KHAKI = "#F0E68C"
WEBSAFE_LAVENDER = "#E6E6FA"
WEBSAFE_LAVENDER_BLUSH = "#FFF0F5"
WEBSAFE_LAWN_GREEN = "#7CFC00"
WEBSAFE_LEMON_CHIFFON = "#FFFACD"
WEBSAFE_LIGHT_BLUE = "#ADD8E6"
WEBSAFE_LIGHT_CORAL = "#F08080"
WEBSAFE_LIGHT_CYAN = "#E0FFFF"
WEBSAFE_LIGHT_GOLDEN_ROD_YELLOW = "#FAFAD2"
WEBSAFE_LIGHT_GRAY = "#D3D3D3"
WEBSAFE_LIGHT_GREEN = "#90EE90"
WEBSAFE_LIGHT_PINK = "#FFB6C1"
WEBSAFE_LIGHT_SALMON = "#FFA07A"
WEBSAFE_LIGHT_SEA_GREEN = "#20B2AA"
WEBSAFE_LIGHT_SKY_BLUE = "#87CEFA"
WEBSAFE_LIGHT_SLATE_GRAY = "#778899"
WEBSAFE_LIGHT_STEEL_BLUE = "#B0C4DE"
WEBSAFE_LIME = "#00FF00"
WEBSAFE_LIME_GREEN = "#32CD32"
WEBSAFE_LINEN = "#FAF0E6"
WEBSAFE_MAROON = "#800000"
WEBSAFE_MEDIUM_AQUAMARINE = "#66CDAA"
WEBSAFE_MEDIUM_BLUE = "#0000CD"
WEBSAFE_MEDIUM_ORCHID = "#BA55D3"
WEBSAFE_MEDIUM_PURPLE = "#9370DB"
WEBSAFE_MEDIUM_SEA_GREEN = "#3CB371"
WEBSAFE_MEDIUM_SLATE_BLUE = "#7B68EE"
WEBSAFE_MEDIUM_SPRING_GREEN = "#00FA9A"
WEBSAFE_MEDIUM_TURQUOISE = "#48D1CC"
WEBSAFE_MEDIUM_VIOLET_RED = "#C71585"
WEBSAFE_MIDNIGHT_BLUE = "#191970"
WEBSAFE_MINT_CREAM = "#F5FFFA"
WEBSAFE_MISTY_ROSE = "#FFE4E1"
WEBSAFE_MOCCASIN = "#FFE4B5"
WEBSAFE_NAVAJO_WHITE = "#FFDEAD"
WEBSAFE_NAVY = "#000080"
WEBSAFE_OLD_LACE = "#FDF5E6"
WEBSAFE_OLIVE = "#808000"
WEBSAFE_OLIVE_DRAB = "#6B8E23"
WEBSAFE_ORANGE = "#FFA500"
WEBSAFE_ORANGE_RED = "#FF4500"
WEBSAFE_ORCHID = "#DA70D6"
WEBSAFE_PALE_GOLDEN_ROD = "#EEE8AA"
WEBSAFE_PALE_GREEN = "#98FB98"
WEBSAFE_PALE_TURQUOISE = "#AFEEEE"
WEBSAFE_PALE_VIOLETRED = "#DB7093"
WEBSAFE_PAPAYA_WHIP = "#FFEFD5"
WEBSAFE_PEACH_PUFF = "#FFDAB9"
WEBSAFE_PERU = "#CD853F"
WEBSAFE_PINK = "#FFC0CB"
WEBSAFE_PLUM = "#DDA0DD"
WEBSAFE_POWDER_BLUE = "#B0E0E6"
WEBSAFE_PURPLE = "#800080"
WEBSAFE_QUARTZ = "#54FF9F"
WEBSAFE_RED = "#FF0000"
WEBSAFE_ROSY_BROWN = "#BC8F8F"
WEBSAFE_ROYAL_BLUE = "#4169E1"
WEBSAFE_SADDLE_BROWN = "#8B4513"
WEBSAFE_SALMON = "#FA8072"
WEBSAFE_SANDY_BROWN = "#F4A460"
WEBSAFE_SEA_GREEN = "#2E8B57"
WEBSAFE_SIENNA = "#A0522D"
WEBSAFE_SILVER = "#C0C0C0"
WEBSAFE_SKY_BLUE = "#87CEEB"
WEBSAFE_SLATE_BLUE = "#6A5ACD"
WEBSAFE_SLATE_GRAY = "#778899"
WEBSAFE_STEEL_BLUE = "#4682B4"
WEBSAFE_TEAL = "#008080"
WEBSAFE_TOMATO = "#FF6347"
WEBSAFE_TURQUOISE = "#40E0D0"
WEBSAFE_VIOLET = "#EE82EE"
WEBSAFE_WHEAT = "#F5DEB3"
WEBSAFE_WHITE = "#FFFFFF"
WEBSAFE_WHITE_SMOKE = "#F5F5F5"
WEBSAFE_YELLOW = "#FFFF00"
WEBSAFE_YELLOW_GREEN = "#9ACD32"
WEBSAFE_ZAPIER = "#29B6F6"
)
