package sharedServices

//goland:noinspection ALL
const (
	AMPERSAND        = "&"
	APOSTROPHE       = "'"
	AT_SIGN          = "@"
	BRACKET_LEFT     = "["
	BRACKET_RIGHT    = "]"
	BRACE_LEFT       = "{"
	BRACE_RIGHT      = "}"
	CARAT            = "^"
	COLON            = ":"
	COMMA            = ","
	DASH             = "-"
	FORWARD_SLASH    = "/"
	ELLIPSIS         = "..."
	EXCLAMATION      = "!"
	HASH_TAG         = "#"
	HYPHEN           = "-"
	PARENTHESE_LEFT  = "("
	PARENTHESE_RIGHT = ")"
	PERCENT_SIGN     = "%"
	PERIOD           = "."
	POUND_SIGN       = "#"
	QUESTION_MARK    = "?"
	QUOTATION_MARKS  = "\""
	SEMI_COLON       = ";"
	STAR             = "*"
	UNDERSCORE       = "_"
)
